##### ANFANG DATEI # 'jobskript.pbs' ####
#####!/bin/bash
#PBS -N p-omp
#PBS -l nodes=2:ppn=24,walltime=00:15:00
#PBS -m n
#PBS -o job_script.out
PROG="/home/oostlander/hr/task04/04-PDE/omp/partdiff-seq"

PROGARGS="14 2 256 1 2 500" 
source /opt/modules/current/Modules/init/bash
#module load mpich2
cd $PBS_O_WORKDIR
#####cat $PBS_NODEFILE
######mpiexec
$PROG $PROGARGS >> timescript.out
echo "fertig"
