##### ANFANG DATEI # 'jobskript.pbs' ####
#####!/bin/bash
#PBS -N pmpi
#PBS -l nodes=1:ppn=12,walltime=00:15:00
#PBS -m n
#PBS -o script.out
PROG="/home/oostlander/hr/task04/04-PDE/mpi/partdiff-par"

PROGARGS="4 2 112 1 2 100" 
source /opt/modules/current/Modules/init/bash
module load mpich2
cd $PBS_O_WORKDIR
#####cat $PBS_NODEFILE
mpiexec -n 12 $PROG $PROGARGS >> timescript.out
########echo "fertig"
